name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/find-my-meme-frontend:latest
          build-args: |
            REACT_APP_FILE_BASEURL=${{ secrets.REACT_APP_FILE_BASEURL }} \
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
